<?php

$modversion['name'] = _MI_EASYWEB_NAME;
$modversion['version'] = 1.00;
$modversion['description'] = _MI_EASYWEB_DESC;
$modversion['credits'] = 'The XOOPS Project';
$modversion['author'] = 'Jan I Pettersen (Xend)<br>( http://www.xendtech.com/ )';
$modversion['help'] = 'images/wysiwyg/easyweb.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'images/easyweb_slogo.jpg';
$modversion['dirname'] = 'easyweb';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'eascont';
$modversion['tables'][1] = 'easyweb';
$modversion['tables'][2] = 'easyweb_startpage';
// Blocks
$modversion['blocks'][1]['file'] = '/easyweb.php';
$modversion['blocks'][1]['name'] = _MI_EASYWEB_1;
$modversion['blocks'][1]['description'] = 'Shows EasyWeb box 1';
$modversion['blocks'][1]['show_func'] = 'b_easyweb_show1';

$modversion['blocks'][2]['file'] = 'easyweb.php';
$modversion['blocks'][2]['name'] = _MI_EASYWEB_2;
$modversion['blocks'][2]['description'] = 'Shows EasyWeb box 2';
$modversion['blocks'][2]['show_func'] = 'b_easyweb_show2';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'easyweb_search';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;

// Smarty
$modversion['use_smarty'] = 1;
